import json

with open('Pipeline_Execution.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

for i, cell in enumerate(nb['cells']):
    if 'source' in cell and len(cell['source']) > 0:
        source_str = ''.join(cell['source'])
        
        # Update Cell 13: Selection by Validation Metrics and NaN handling
        if "endog=df_monthly['kWh_Total']" in source_str:
            cell['source'] = [
                "import pandas as pd\n",
                "import numpy as np\n",
                "import os\n",
                "from itertools import product\n",
                "from statsmodels.tsa.statespace.sarimax import SARIMAX\n",
                "from sklearn.metrics import mean_squared_error, mean_absolute_error\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "# 1. Preparación de Datos\n",
                "if 'df_monthly' not in locals():\n",
                "    df_monthly = pd.read_csv('data/monthly-data.csv')\n",
                "    df_monthly['Mes'] = pd.to_datetime(df_monthly['Mes'])\n",
                "\n",
                "df_sarimax = df_monthly.set_index('Mes').sort_index()\n",
                "target = 'kWh_Total'\n",
                "exog_cols = ['Irradiancia_It_mean', 'Temperatura_Tt_mean', 'Viento_Wt_mean']\n",
                "\n",
                "train_data = df_sarimax.iloc[:-12]\n",
                "val_data = df_sarimax.iloc[-12:]\n",
                "\n",
                "print(f\"Entrenamiento: {train_data.index.min()} a {train_data.index.max()}\")\n",
                "print(f\"Validación: {val_data.index.min()} a {val_data.index.max()}\")\n",
                "\n",
                "# 2. Grid Search (Selección por MAPE en Validación)\n",
                "p_values, d_values, q_values = [1, 2], [0], [1, 2]\n",
                "P_values, D_values, Q_values, m = [1], [1], [1], 12\n",
                "\n",
                "resultados = []\n",
                "combinaciones = list(product(p_values, d_values, q_values, P_values, D_values, Q_values))\n",
                "print(f'\\nProbando {len(combinaciones)} combinaciones...')\n",
                "\n",
                "for p, d, q, P, D, Q in combinaciones:\n",
                "    try:\n",
                "        modelo = SARIMAX(\n",
                "            endog=train_data[target],\n",
                "            exog=train_data[exog_cols],\n",
                "            order=(p, d, q),\n",
                "            seasonal_order=(P, D, Q, m),\n",
                "            enforce_stationarity=False,\n",
                "            enforce_invertibility=False\n",
                "        ).fit(disp=False)\n",
                "        \n",
                "        pred = modelo.forecast(steps=len(val_data), exog=val_data[exog_cols])\n",
                "        \n",
                "        # Manejo de NaNs en predicción\n",
                "        if np.any(np.isnan(pred)):\n",
                "            continue\n",
                "            \n",
                "        rmse = np.sqrt(mean_squared_error(val_data[target], pred))\n",
                "        mae = mean_absolute_error(val_data[target], pred)\n",
                "        mape = np.mean(np.abs((val_data[target] - pred) / val_data[target])) * 100\n",
                "        \n",
                "        resultados.append({\n",
                "            'params': f'({p},{d},{q})({P},{D},{Q})_{m}',\n",
                "            'RMSE': rmse,\n",
                "            'MAE': mae,\n",
                "            'MAPE': mape,\n",
                "            'AIC': modelo.aic\n",
                "        })\n",
                "    except:\n",
                "        pass\n",
                "\n",
                "resultados_df = pd.DataFrame(resultados).sort_values('MAPE')\n",
                "print('\\n--- Ranking de Modelos (Top 5 por MAPE en Validación) ---')\n",
                "display(resultados_df.head())\n",
                "\n",
                "best_params_str = resultados_df.iloc[0]['params']\n",
                "print(f'\\nModelo Ganador Seleccionado: {best_params_str}')\n"
            ]

        # Update Cell 14 (Visualization and Metrics Display)
        if "import matplotlib.pyplot as plt" in source_str and "final_model" in source_str:
            cell['source'] = [
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "import re\n",
                "\n",
                "# 1. Re-entrenar el mejor modelo\n",
                "best_row = resultados_df.iloc[0]\n",
                "nums = re.findall(r'\\d+', best_row['params'])\n",
                "p, d, q, P, D, Q, m = map(int, nums)\n",
                "\n",
                "final_model = SARIMAX(\n",
                "    endog=train_data[target],\n",
                "    exog=train_data[exog_cols],\n",
                "    order=(p, d, q),\n",
                "    seasonal_order=(P, D, Q, m),\n",
                "    enforce_stationarity=False,\n",
                "    enforce_invertibility=False\n",
                ").fit(disp=False)\n",
                "\n",
                "val_pred = final_model.forecast(steps=len(val_data), exog=val_data[exog_cols])\n",
                "\n",
                "# 2. Gráfica de Predicción vs Real\n",
                "plt.figure(figsize=(12, 7))\n",
                "plt.plot(train_data.index, train_data[target], label='Entrenamiento', color='gray', alpha=0.4)\n",
                "plt.plot(val_data.index, val_data[target], label='Real (Validación)', marker='o', color='royalblue', linewidth=2)\n",
                "plt.plot(val_data.index, val_pred, label='Predicción SARIMAX', marker='x', linestyle='--', color='crimson', linewidth=2)\n",
                "\n",
                "# Mostrar métricas en la gráfica\n",
                "metrics_text = f\"RMSE: {best_row['RMSE']:,.0f}\\nMAE: {best_row['MAE']:,.0f}\\nMAPE: {best_row['MAPE']:.2f}%\"\n",
                "plt.gca().text(0.02, 0.95, metrics_text, transform=plt.gca().transAxes, \n",
                "             bbox=dict(facecolor='white', alpha=0.8, edgecolor='gray'), verticalalignment='top')\n",
                "\n",
                "plt.title(f'Validación SARIMAX: {best_row[\"params\"]}', fontsize=14, fontweight='bold')\n",
                "plt.xlabel('Mes', fontsize=12)\n",
                "plt.ylabel('kWh Total', fontsize=12)\n",
                "plt.xticks(rotation=90) # Labels verticales\n",
                "plt.legend(loc='upper right')\n",
                "plt.grid(True, linestyle='--', alpha=0.6)\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "# 3. Exportar a CSV\n",
                "metrics_df = pd.DataFrame({\n",
                "    'Metric': ['RMSE', 'MAE', 'MAPE'],\n",
                "    'Value': [best_row['RMSE'], best_row['MAE'], best_row['MAPE']]\n",
                "})\n",
                "metrics_df.to_csv('data/sarimax_validation_metrics.csv', index=False)\n",
                "print(\"Métricas guardadas en 'data/sarimax_validation_metrics.csv'\")\n"
            ]

with open('Pipeline_Execution.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
